/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as CustomPostImport } from './routes/custom-post'
import { Route as AppliedImport } from './routes/applied'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const CustomPostRoute = CustomPostImport.update({
  id: '/custom-post',
  path: '/custom-post',
  getParentRoute: () => rootRoute,
} as any)

const AppliedRoute = AppliedImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/applied': {
      id: '/applied'
      path: '/applied'
      fullPath: '/applied'
      preLoaderRoute: typeof AppliedImport
      parentRoute: typeof rootRoute
    }
    '/custom-post': {
      id: '/custom-post'
      path: '/custom-post'
      fullPath: '/custom-post'
      preLoaderRoute: typeof CustomPostImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/custom-post': typeof CustomPostRoute
  '/profile': typeof ProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/custom-post': typeof CustomPostRoute
  '/profile': typeof ProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/applied': typeof AppliedRoute
  '/custom-post': typeof CustomPostRoute
  '/profile': typeof ProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/applied' | '/custom-post' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/applied' | '/custom-post' | '/profile'
  id: '__root__' | '/' | '/applied' | '/custom-post' | '/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppliedRoute: typeof AppliedRoute
  CustomPostRoute: typeof CustomPostRoute
  ProfileRoute: typeof ProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppliedRoute: AppliedRoute,
  CustomPostRoute: CustomPostRoute,
  ProfileRoute: ProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/applied",
        "/custom-post",
        "/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/applied": {
      "filePath": "applied.tsx"
    },
    "/custom-post": {
      "filePath": "custom-post.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
